README.md, lib/alamo.js, lib/app-setups.js, lib/auto_builds.js, lib/builds.js, lib/config.js, lib/github.js, lib/lifecycle.js, lib/releases.js, sql/create.sql, sql/select_auto_releases.sql, test/app-setups.js, test/apps.js
1. Fixes incorrect image being pulled from conventions, now goes back to stack API for running image.
2. Removes old queue code to give preference to built in async/await
3. Enables auto build to work without authorizaiton, automatically insert auto build workflow for new app.
=> COBRA-1556 - Clean up app-setups issues

Dockerfile, index.js, lib/alamo.js, lib/builds.js, lib/common.js, lib/git.js, lib/hook-types/https.js, lib/hooks.js, lib/http_helper.js, lib/log-drains.js, lib/logs.js, lib/metrics.js, lib/salt_tokens.js, test/addon-multiple.js, test/git.js, test/hooks.js, test/invoices.js, test/regions.js, test/stacks.js, test/support/worker2-app/Dockerfile, test/support/worker2-app/worker.js, worker.js
Update version to Node 12 and remove deprecated API calls
=> update node, remove url.parse, crypto.createCipher

lib/lifecycle.js, test/app-setups.js, test/lifecycle.js, test/support/attach-app/Dockerfile, test/support/formations-app/Dockerfile, test/support/hooks-app/Dockerfile, test/support/lifecycle-app/Dockerfile, test/support/lifecycle-app/index.js, test/support/no-hidden-file/somedir/Dockerfile, test/support/pipelines1-app/Dockerfile, test/support/pipelines2-app/Dockerfile, test/support/pipelines3-app/Dockerfile, test/support/pipelines4-app/Dockerfile, test/support/sample-app/Dockerfile, test/support/worker-app/Dockerfile, test/support/worker2-app/Dockerfile
RESTART environment variable isn't needed anymore. Removed and tests updated
Also update all of the test app docker images to node v12 (alpine)
=> Remove RESTART variable, misc fixes

index.js, lib/salt_tokens.js
Trevor provided documentation in another pull request (thanks @trevorlinton)
=> hooks table migration

lib/events.js, lib/releases.js, package-lock.json, sql/select_pipeline_coupling.sql, sql/select_pipeline_coupling_by_app.sql, sql/select_pipeline_couplings.sql, sql/select_pipeline_couplings_by_pipeline.sql, sql/select_pipeline_couplings_by_stage.sql, sql/select_release.sql, sql/select_releases.sql
Fix the returned "current" release on pipeline coupling end point rather than the latest release.
=> COBRA-3013

lib/hooks.js
not all valid hooks were present in the `allowed_events` array, so check the master list of hooks and descriptions instead
=> one source of truth for hooks

test/addons.js
Messed up the merging master in the last PR... shouldn't have used the web editor
=> fix addon tests

docs/API-Reference.md, lib/events.js, lib/hooks.js
Paves the way for one-off scans using services like Detectify
=> Add "security_scan" webhook

package-lock.json, package.json
These were the dependencies I could upgrade without breaking things. The remaining dependencies should be upgraded one-by-one.
=> COBRA-3825 - Upgrade dependencies

.vscode/launch.json, package-lock.json, package.json
- Add dev script that runs nodemon
- Add npm run dev script to VS Code debug configurations
=> COBRA-3835: npm dev script

lib/events.js, lib/git.js, sql/create.sql, sql/select_build_scm_metadata.sql, sql/update_build_scm_metadata.sql
- Create the GH deployment at the start of the build, rather than on release
- Update GH deployment to `in_progress` or `failed` on build status change
=> COBRA-3834: GitHub deployment on build

lib/hook-types/slack.js, test/hooks.js
`config_change` event fired on app `robots-calaway`
```
{
"action": "config_change",
"app": {
"name": "robots",
"id": "56e63fb9-57b1-4af3-9290-5f1ff5e9a0ea"
},
"space": {
"name": "calaway"
},
"changes": [
{
"type": "update",
"name": "FOO"
},
{
"type": "delete",
"name": "BAZ"
},
{
"type": "create",
"name": "BUZ"
}
],
"config_vars": {
"PORT": "5000",
"FOO": "1",
"BAR": "5",
"BUZ": "0"
}
}
```
Config var change(s) on app `robots-calaway`:
• Updated `FOO`
• Deleted `BAZ`
• Created `BUZ`
=> COBRA-3829: Format slack config change alert

lib/dynos.js
=> missing '-' in dyno id

lib/dynos.js
=> put the hyphen in the wrong place

test/.eslintrc.json, test/filters-cors.js
Add CORS tests for:
- simple request from
- same origin
- disallowed origin
- allowed origin
- preflight request from
- same origin
- disallowed origin
- allowed origin
=> COBRA-3754: CORS filters testing

sql/create.sql
Only material change is in the first commit. Second commit is only formatting.
=> COBRA-3940: Bug fix on create.sql

docs/Formations.md, index.js, lib/alamo.js, lib/dynos.js, lib/formations.js, lib/lifecycle.js, lib/releases.js, package-lock.json, sql/create.sql, sql/insert_formation.sql, sql/select_formations.sql
Creating a formation with the `oneoff` flag set to true marks the formation as a "one-off". This instructs Akkeris to create a single pod and not have it restart when the container exits.
Provides ability to override app environment variables as well as the app image.
=> One-Off Dynos

index.js, lib/recommendations.js, sql/create.sql, sql/insert_recommendation.sql, sql/select_recommendation_by_primary_key.sql, sql/select_recommendation_resource_type.sql, sql/select_recommendation_resource_types.sql, sql/update_recommendation_details.sql
Adds endpoints that services will need to be able to add and update recommendations.
=> Recommendations API Service Endpoints

lib/apps.js
This should make it so it doesn't say System every time maintenance mode is changed
=> add username to maintenance mode toggle

docs/API-Reference.md, docs/Recommendations.md, index.js, lib/recommendations.js, package-lock.json, sql/create.sql, sql/select_recommendation_by_id.sql, sql/select_recommendation_resource_type.sql, sql/select_recommendation_resource_types.sql, sql/select_recommendations_by_app.sql
- Added endpoints to fetch recommendations
- Added API documentation
- Improve "resource type" validation - Now a description and valid recommendation `details` fields are provided in the `resource_type` endpoint. This ensures that recommendations have the correct fields for each action. See the docs for more info
- Ran `npm audit fix`
=> COBRA-4068: User endpoints for recommendations-api

index.js, lib/recommendations.js, sql/create.sql, sql/delete_recommendation_by_id.sql, sql/select_recommendation_by_id.sql, sql/select_recommendation_by_primary_key.sql, sql/select_recommendations_by_app.sql, sql/update_recommendation_details.sql
Need to be able to delete recommendations that are no longer valid
=> Add ability to delete recommendations
